spring:
  datasource:
    url: jdbc:postgresql://192.168.1.67:5432/postgres
    username: postgres
    password=: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: fyongtiendong@gmail.com
    password: djmdtegfrnnzdsdo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

upload:
  folder: src/main/resources/uploads/
